### ISSUE TITLE
 Error in cut_Tu (line 52)

### ISSUE THREAD

**Issue by surajmunale** [xiumingzhang/grabcut#1]
Hello,

I am trying to execute this code but it is giving error as below:

Error in cut_Tu (line 52)
mrf = BK_Create(no_nodes);

Error in grabcut (line 64)
    [pix_U, E] = cut_Tu(pix_U, im_sub, alpha, gmm_U, gmm_B, pairwise);

Error in main (line 5)
im_out = grabcut(im_in, GAMMA);

Please help me to resolve this issue.

Thanks,

**Comment by xiumingzhang** [comment]
Hi there,

I guess you are not on OS X? If not, you will need to re-build the `bin_graphcuts` package (i.e., [generate the mex file](http://www.mathworks.com/help/matlab/matlab_external/what-you-need-to-build-mex-files.html)). Have you done that?

Cheers,
Ming

**Comment by surajmunale** [comment]
Hello,
Thanks for your prompt reply. :)

We are not on OS-x. and we have not rebuild the bin_graphcuts package. Could you please provide steps to rebuild.

Thanks

**Comment by xiumingzhang** [comment]
Hi,

Simply do `mex bk_matlab.cpp`.

Cheers,
Ming

**Comment by surajmunale** [comment]
Hello, 
I run the provided command. I get below error:

> > mex bin_graphcuts/bk_matlab.cpp
> > lcc preprocessor error: bin_graphcuts\bk_matlab.cpp:3 Could not find include file <map> 
> > lcc preprocessor error: bin_graphcuts\bk_matlab.cpp:4 Could not find include file <string> 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 99  syntax error; found `<' expecting`;' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 99  skipping `<' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 99  syntax error; found`Type' expecting `;' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 99  syntax error; found`>' expecting `;' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 99  skipping`>' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 99  syntax error; found `Block' expecting`;' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 100  syntax error; found `{' expecting`;' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 100  skipping `{' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 101  syntax error; found`:' expecting `;' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 101  skipping`:' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 106  illegal initialization for parameter `err_function' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 106  redeclaration of`Block' previously declared at bin_graphcuts\block.h 99 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 106  undeclared identifier `first' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 106  undeclared identifier`last' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 106  undeclared identifier `block_size' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 106  undeclared identifier`error_function' 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 106  operands of = have illegal types `int' and`pointer to void function(pointer to char)' 
> > Warning bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 106  missing return value 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 109  unrecognized declaration 
> > Error bin_graphcuts\bk_matlab.cpp: bin_graphcuts\block.h: 109  too many errors 

  C:\PROGRA~1\MATLAB\R2013A\BIN\MEX.PL: Error: Compile of 'bin_graphcuts\bk_matlab.cpp' failed. 

Error using mex (line 206)
Unable to complete successfully.
